"""
tcd — Add speaker labels to a whisper.cpp transcript
Usage:  tcd <audio.wav> <transcript.vtt>
Output: prints the transcript with SPEAKER_00, SPEAKER_01, etc. prefixed on each line.

How it works:
  1. Runs pyannote/speaker-diarization-3.1 on the audio to detect who speaks when.
  2. Parses a WebVTT file (generated by whisper.cpp -ovtt) for timestamps + text.
  3. Assigns the best-matching speaker label to each segment by temporal overlap.

Why VTT and not TXT:
  whisper.cpp -otxt strips timestamps, making speaker alignment impossible.
  -ovtt preserves timestamps. tc generates a temp .vtt when diarization is enabled,
  passes it here, then deletes it. The user-facing output is still plain .txt.

Dependencies:
  - Python venv at ~/.venv/tc-diarize with pyannote.audio installed
  - HF_TOKEN env var (READ token from https://huggingface.co/settings/tokens)
  - Licenses accepted on HuggingFace (one-time, per account):
      https://huggingface.co/pyannote/speaker-diarization-3.1
      https://huggingface.co/pyannote/segmentation-3.0
      https://huggingface.co/pyannote/speaker-diarization-community-1
  - Models are downloaded and cached locally on first run (~1.5 GB total).
    After that, no internet access is needed.

Installed via: dotfiles/install.sh
Context: written in March 2026 with pyannote.audio 4.x
  - API: token= (not use_auth_token=)
  - Pipeline returns DiarizeOutput — use .speaker_diarization.itertracks()
"""

import sys
import os
import re


def ts_to_seconds(ts):
    h, m, s = ts.split(":")
    return int(h) * 3600 + int(m) * 60 + float(s)


def get_speaker(start, end, segments):
    best_speaker = None
    best_overlap = 0
    for seg_start, seg_end, speaker in segments:
        overlap = max(0, min(end, seg_end) - max(start, seg_start))
        if overlap > best_overlap:
            best_overlap = overlap
            best_speaker = speaker
    return best_speaker or "SPEAKER_?"


def parse_vtt(path):
    """Parse a WebVTT file, return list of (start_sec, end_sec, text)."""
    segments = []
    ts_pattern = re.compile(
        r'(\d{2}:\d{2}:\d{2}[\.,]\d+)\s*-->\s*(\d{2}:\d{2}:\d{2}[\.,]\d+)'
    )
    with open(path) as f:
        lines = f.readlines()

    i = 0
    while i < len(lines):
        m = ts_pattern.match(lines[i].strip())
        if m:
            t0 = ts_to_seconds(m.group(1).replace(",", "."))
            t1 = ts_to_seconds(m.group(2).replace(",", "."))
            i += 1
            text_lines = []
            while i < len(lines) and lines[i].strip():
                text_lines.append(lines[i].strip())
                i += 1
            text = " ".join(text_lines).strip()
            if text:
                segments.append((t0, t1, text))
        else:
            i += 1

    return segments


def main():
    if len(sys.argv) != 3:
        print("Usage: tcd <audio.wav> <transcript.vtt>", file=sys.stderr)
        sys.exit(1)

    audio_path = sys.argv[1]
    vtt_path = sys.argv[2]

    hf_token = os.environ.get("HF_TOKEN")
    if not hf_token:
        print("❌ HF_TOKEN not set. Add it to ~/.zshrc", file=sys.stderr)
        sys.exit(1)

    for path in [audio_path, vtt_path]:
        if not os.path.exists(path):
            print(f"❌ File not found: {path}", file=sys.stderr)
            sys.exit(1)

    print("🔊 Loading diarization model...", file=sys.stderr)
    from pyannote.audio import Pipeline
    import torch

    pipeline = Pipeline.from_pretrained(
        "pyannote/speaker-diarization-3.1",
        token=hf_token
    )

    if torch.backends.mps.is_available():
        pipeline.to(torch.device("mps"))
        print("   Using Apple Silicon MPS", file=sys.stderr)

    print("🎙️  Running speaker diarization...", file=sys.stderr)
    diarization = pipeline(audio_path)

    speaker_segments = [
        (turn.start, turn.end, speaker)
        for turn, _, speaker in diarization.speaker_diarization.itertracks(yield_label=True)
    ]

    transcript_segments = parse_vtt(vtt_path)

    output_lines = []
    for t0, t1, text in transcript_segments:
        speaker = get_speaker(t0, t1, speaker_segments)
        output_lines.append(f"[{speaker}] {text}")

    print("\n".join(output_lines))


if __name__ == "__main__":
    main()
